# Generated by Django 4.2.4 on 2023-09-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIsite', '0005_guestuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='guest_ips',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='guest_msgs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='guest_session',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
