# Generated by Django 4.2.4 on 2023-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIsite', '0006_remove_guestuser_guest_ips_guestuser_guest_msgs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_ips',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='balance',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
