# Generated by Django 4.2.4 on 2023-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIsite', '0007_delete_guestuser_userdata_is_guest_userdata_user_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chats_limit',
            field=models.IntegerField(default=1),
        ),
    ]
