# Generated by Django 4.2.4 on 2023-09-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIsite', '0008_product_chats_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIsite.userdata')),
            ],
        ),
    ]
