# Generated by Django 4.2.4 on 2023-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIsite', '0009_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='token_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.CharField(max_length=32),
        ),
    ]
